# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 371d332719fce95b0c31a35c2c72ed8fc56d54406983059089cd6fe20633c8da8dd10e523b64eaf0c53387752059a264242ac1345b59c8116f21217e43a17273

test:
  secret_key_base: fcb029c1c16ab6b1f4c8b0f74db7688efa8ef6b3874c46a6831e8eccdf9fe2fea12e7821262a2d08a21166c2e2d473587b090753cf052572058d4de2fcf85726

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
